		SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     3 NDI,NSHR,NTENS,NSTATEV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
C
       INCLUDE 'ABA_PARAM.INC'
C
       CHARACTER*80 CMNAME
       DIMENSION STRESS(NTENS),STATEV(NSTATEV),
     1 DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3 PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3),
     4 JSTEP(4), BBAR(6), DISTGR(3,3)

       PARAMETER( ZERO=0.D0, ONE=1.D0, TWO=2.D0, THREE=3.D0 )  
C
 
        REAL*8 G, JM, D1 
        REAL*8 TERM1, TERM2, TRFRM, DET, TRBBAR, TERM3, TERM4 
C


          G=PROPS(1)
          JM=PROPS(2) 
          D1=PROPS(3)


          DET=DFGRD1(1,1)*DFGRD1(2,2)*DFGRD1(3,3)
     1    -DFGRD1(1,2)*DFGRD1(2,1)*DFGRD1(3,3)
          IF(NSHR == 3) THEN
          DET=DET+DFGRD1(1,2)*DFGRD1(2,3)*DFGRD1(3,1)
     1          +DFGRD1(1,3)*DFGRD1(3,2)*DFGRD1(2,1)
     2          -DFGRD1(1,3)*DFGRD1(3,1)*DFGRD1(2,2)
     3          -DFGRD1(2,3)*DFGRD1(3,2)*DFGRD1(1,1)
          END IF
           
C
C         F_Bar F_Bar=DET(F)^(-1/3)*F
C
          TRFRM=DET**(-ONE/THREE)
          DO K1=1,3
           DO K2=1,3
            DISTGR(K2,K1)=TRFRM*DFGRD1(K2,K1)
           END DO
          END DO
 
C
C         B_Bar=F_Bar*F_BarT
C

          BBAR(1)=DISTGR(1,1)**2+DISTGR(1,2)**2+DISTGR(1,3)**2
         
          BBAR(2)=DISTGR(2,1)**2+DISTGR(2,2)**2+DISTGR(2,3)**2   
          BBAR(3)=DISTGR(3,3)**2+DISTGR(3,1)**2+DISTGR(3,2)**2   
          BBAR(4)=DISTGR(1,1)*DISTGR(2,1)+DISTGR(1, 2)*DISTGR(2,2)  
     1 		+DISTGR(1,3)*DISTGR(2,3)
          IF(NSHR == 3) THEN
			BBAR(5)=DISTGR(1,1)*DISTGR(3,1)+DISTGR(1,2)*DISTGR(3,2)   
     1 			+DISTGR(1,3)*DISTGR(3,3)
			BBAR(6)=DISTGR(2,1)*DISTGR(3,1)+DISTGR(2,2)*DISTGR(3,2)   
     1 			+DISTGR(2,3)*DISTGR(3,3)
          END IF


              TRBBAR=(BBAR(1)+BBAR(2)+BBAR(3))/THREE  

      
			  TERM1=G/DET*(ONE-(THREE*TRBBAR-THREE)/JM)**(-ONE)
              TERM2=TWO*G/DET/JM*(ONE-(THREE*TRBBAR-THREE)/JM)**(-TWO)
              TERM3=(TWO/D1)*(TWO*DET-ONE)
              TERM4=(TWO/D1)*(DET-ONE)
              
			  

          
          DO K1=1,NDI
			STRESS(K1)=TERM1*(BBAR(K1)-TRBBAR)+TERM4
          END DO
          DO K1=NDI+1,NDI+NSHR
			STRESS(K1)=TERM1*BBAR(K1)
          END DO

C
    
         DDSDDE(1,1)=TWO/THREE*TERM1*(BBAR(1)+TRBBAR)+ 
     1 		TERM2*(BBAR(1)**TWO-TWO*TRBBAR*BBAR(1)+TRBBAR**TWO)+TERM3 
          DDSDDE(2,2)=TWO/THREE*TERM1*(BBAR(2)+TRBBAR)+
     1 		TERM2*(BBAR(2)**TWO-TWO*TRBBAR*BBAR(2)+TRBBAR**TWO)+TERM3
          DDSDDE(3,3)=TWO/THREE*TERM1*(BBAR(3)+TRBBAR)+
     1 		TERM2*(BBAR(3)**TWO-TWO*TRBBAR*BBAR(3)+TRBBAR**TWO)+TERM3 
	      DDSDDE(1,2)=TWO/THREE*TERM1*(TRBBAR-BBAR(1)
     1 		-BBAR(2))+TERM2*(BBAR(1)*BBAR(2)
     2 		-TRBBAR*(BBAR(1)+BBAR(2))+TRBBAR**TWO)+TERM3
          DDSDDE(1,3)=TWO/THREE*TERM1*(TRBBAR-BBAR(3)-
     1 		BBAR(1))+TERM2*(BBAR(3)*BBAR(1)-TRBBAR*(BBAR(3)+
     2 		BBAR(1))+TRBBAR**TWO)+TERM3
          DDSDDE(2,3)=TWO/THREE*TERM1*(TRBBAR-BBAR(2)-BBAR(3))+
     1 		TERM2*(BBAR(2)*BBAR(3)-TRBBAR*(BBAR(2)+BBAR(3))+
     2 		TRBBAR**TWO)+TERM3
          DDSDDE(1,4)=ONE/THREE*TERM1*BBAR(4)+TERM2*(BBAR(1)-
     1 		TRBBAR)*BBAR(4)
          DDSDDE(2,4)=ONE/THREE*TERM1*BBAR(4)+TERM2*(BBAR(2)-
     1 		TRBBAR)*BBAR(4)
          DDSDDE(3,4)=-TWO/THREE*TERM1*BBAR(4)+TERM2*(BBAR(3)-
     1 		TRBBAR)*BBAR(4)
          DDSDDE(4,4)=ONE/TWO*TERM1*(BBAR(1)+BBAR(2))
          IF(NSHR == 3) THEN
          DDSDDE(1,5)=ONE/THREE*TERM1*BBAR(5)+TERM2*(BBAR(1)-
     1 		TRBBAR)*BBAR(5)
          DDSDDE(2,5)=-TWO/THREE*TERM1*BBAR(5)+TERM2*(BBAR(2)-
     1 		TRBBAR)*BBAR(5) 
          DDSDDE(3,5)=ONE/THREE*TERM1*BBAR(5)+TERM2*(BBAR(3)-
     1 		TRBBAR)*BBAR(5)
          DDSDDE(1,6)=-TWO/THREE*TERM1*BBAR(6)+TERM2*(BBAR(1)-
     1 		TRBBAR)*BBAR(6)
          DDSDDE(2,6)=ONE/THREE*TERM1*BBAR(6)+TERM2*(BBAR(2)-
     1 		TRBBAR)*BBAR(6)
          DDSDDE(3,6)=ONE/THREE*TERM1*BBAR(6)+TERM2*(BBAR(3)-
     1 		TRBBAR)*BBAR(6)
          DDSDDE(5,5)=ONE/TWO*TERM1*(BBAR(3)+BBAR(1))+
     1 		TERM2*BBAR(5)**TWO
          DDSDDE(6,6)=ONE/TWO*TERM1*(BBAR(3)+BBAR(2))+
     1 		TERM2*BBAR(6)**TWO
          DDSDDE(4,5)=ONE/TWO*TERM1*BBAR(6)+TERM2*BBAR(4)*BBAR(5)
          DDSDDE(4,6)=ONE/TWO*TERM1*BBAR(5)+TERM2*BBAR(4)*BBAR(6)
          DDSDDE(5,6)=ONE/TWO*TERM1*BBAR(4)+TERM2*BBAR(5)*BBAR(6)
          END IF

          DO K1=1, NTENS
           DO K2=1, K1-1
            DDSDDE(K1,K2)=DDSDDE(K2, K1)
           END DO
          END DO
C
          RETURN 
          END